context:
  name: mean-average-precision
  version: 2024.01.05.0
  python_min: "3.9" # remove this line once https://github.com/prefix-dev/rattler-build/pull/1122 is available

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/bes-dev/mean_average_precision/archive/refs/tags/${{ version }}.tar.gz
  sha256: b25dda0fdcf1f55d4ae8b9848fb1154369e87323bf472f9cd74da10cbaf992d0

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - numpy
    - pandas

tests:
  - python:
      imports:
        - mean_average_precision
      pip_check: true

about:
  summary: Mean Average Precision evaluator for object detection.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/bes-dev/mean_average_precision/

extra:
  recipe-maintainers:
    - hadim
